### ISSUE TITLE
Extractor emits duplicate symbol id `e92934d0fcd91dd7` — investigate Tree-sitter adapter

### ISSUE THREAD

**Issue by ahmadzubair9655** [ahmadzubair9655/graphify-plus#26]
While running \`gp init\` on a 450-file Next.js + Sanity TS repo (\`/Users/mac/Downloads/SMART-ENERGIE-WEBSITE-CLEAN/smart-energie\`), the store layer flagged one duplicate symbol id:

\`\`\`
replace_all: dropped 1 duplicate symbol id(s); samples=['e92934d0fcd91dd7']
\`\`\`

Surfaced by the WARNING introduced in #25, which dedupes by id (last-write-wins) so init no longer aborts on the \`UNIQUE(symbols.id)\` constraint.

## Likely causes
- TS function overload signatures collapsing to the same id.
- \`default\` export collision across two files producing the same hash input.
- Two adapters (TS + TSX, or TS + JSX-aware) both claiming the same node.
- Symbol id hashing input not including enough disambiguators (path + span + kind + qualified_name).

## Investigation
1. Add a debug logger in the Tree-sitter TS/TSX adapter that prints \`(path, span, kind, qualified_name) -> id\` for any id collision within a single parse pass.
2. Re-run \`gp init\` against the repro repo and capture which two symbols hash to \`e92934d0fcd91dd7\`.
3. Decide: fix the id-input recipe, or accept overloads as legitimately-merged symbols.

## Out of scope for this issue
The dedupe stopgap in #25 is intentional and should remain — it's the right contract for \`replace_all\`. This issue is about the upstream extractor producing the duplicate in the first place.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
